---
title: "detrendr examples"
output: pdf_document
---

## Some examples of baseline fitting with detrendr

```{r load, include=FALSE, echo=FALSE, cache=FALSE}
library(Matrix)
library(devtools)
library(roxygen2)
library(Rcpp)
load_all("../Code/detrendr")


```

```{r simulate}

simulate <- function(n, k){
  x <- seq(1/n, 1, length.out=n)
  f <- 2*(x + 2)^2 + 3*cos(3*pi*x)
  tau <- 5e4
  g1 <- 40*exp(-tau*(x-0.3)^2)
  g2 <- 30*exp(-tau/2*(x-0.58)^2)
  g4 <- 45*exp(-tau/7*(x-0.6)^2)
  g3 <- 37*exp(-tau*(x-0.63)^2)
  y <- f + g1 + g2 + g3 + g4 + rnorm(n)
  D <- get_Dk(n, k)
  M <- diag(n) + crossprod(D)
  cholM <- as.matrix(chol(M))
  return(list(y=y, f=f, x=x, D=D, M=M, cholM=cholM))
}
```


## Current timing experiments
```{r timing, include=TRUE, echo=TRUE, cache=TRUE}
nSeq <- seq(100, 1500, 200)
timing <- data.frame(n=nSeq, R = NA, C=NA)
tau <- 0.01
lambda <- 10
step <- 1

for (i in 1:length(nSeq)){
  simData <- simulate(nSeq[i], 3)
  y <- simData$y
  theta <- simData$y
  D <- simData$D
  eta <- matrix(D%*%theta)
  M <- simData$M
  cholM <- simData$cholM
  timing$R[i] <- system.time( 
      multi_step_R <- spingarn_multi_step_R(theta, eta, y, D, M, lambda, 
                                            tau, step, 100))[3]
  timing$C[i] <- system.time(
    multi_step <- spingarn_multi_step(theta, eta, y, D, cholM,
                                     lambda, tau, step, 100))[3]
}


plot(C~n, timing, type="l", col="blue", ylab="Elapsed Time (s) per 100 iterations", main = "R code is in black, C in blue")
lines(R~n, timing, type="l")
```


## Convergence when n=100, lambda = 10
```{r convergence, include=TRUE, echo=TRUE, cache=TRUE}

n <- 500
simData <- simulate(n, 3)

y <- simData$y
theta <- simData$y
D <- simData$D
eta <- matrix(D%*%theta)
M <- simData$M
cholM <- simData$cholM
tau <- 0.05
lambda <- 10
step <- 1

max_iter <- 70000
rerr <- double(max_iter-1)
THx <- matrix(NA, n, max_iter)
for (iter in 1:max_iter) {
  one_step <- spingarn_one_step_R(theta, eta, y, D, M, lambda, tau, step)
  theta <- one_step[[1]]
  eta <- one_step[[2]]
  THx[,iter] <- prox_f1(theta, y, tau)
  if (iter > 1){
    rerr[iter] <- norm(as.matrix(THx[,iter] - THx[,iter-1]),'f')/
                    (1 + norm(THx[,iter,drop=FALSE], 'f'))
  }
}
theta_last <- prox_f1(theta, y, tau)

par(mfrow=c(2,1), mar=c(3,4,1,1))
plot(log(rerr), type="l")

plot(simData$x,simData$f,type='l',col='blue',
ylim=c(min(y),max(y)), lwd=3,ylab="", xlab="")
points(simData$x,y, cex=.6)
lines(simData$x,theta_last,col='red', lwd=3)

```

## Convergence when n=1000, lambda = 100
```{r convergence2, include=TRUE, echo=FALSE, cache=TRUE}

n <- 1000
simData <- simulate(n, 3)

y <- simData$y
theta <- simData$y
D <- simData$D
eta <- matrix(D%*%theta)
M <- simData$M
cholM <- simData$cholM
tau <- 0.05
lambda <- 100
step <- 1

max_iter <- 70000
rerr <- double(max_iter-1)
THx <- matrix(NA, n, max_iter)
for (iter in 1:max_iter) {
  one_step <- spingarn_one_step_R(theta, eta, y, D, M, lambda, tau, step)
  theta <- one_step[[1]]
  eta <- one_step[[2]]
  THx[,iter] <- prox_f1(theta, y, tau)
  if (iter > 1){
    rerr[iter] <- norm(as.matrix(THx[,iter] - THx[,iter-1]),'f')/
                    (1 + norm(THx[,iter,drop=FALSE], 'f'))
  }
}
theta_last <- prox_f1(theta, y, tau)

par(mfrow=c(2,1), mar=c(3,4,1,1))
plot(log(rerr), type="l")

plot(simData$x,simData$f,type='l',col='blue',
ylim=c(min(y),max(y)), lwd=3,ylab="", xlab="")
points(simData$x,y, cex=.6)
lines(simData$x,theta_last,col='red', lwd=3)

```

## Convergence when n=2000, lambda = 100
```{r convergence3, include=TRUE, echo=FALSE, cache=TRUE}

n <- 2000
simData <- simulate(n, 3)

y <- simData$y
theta <- simData$y
D <- simData$D
eta <- matrix(D%*%theta)
M <- simData$M
cholM <- simData$cholM
tau <- 0.05
lambda <- 100
step <- 1

max_iter <- 70000
rerr <- double(max_iter-1)
THx <- matrix(NA, n, max_iter)
for (iter in 1:max_iter) {
  one_step <- spingarn_one_step_R(theta, eta, y, D, M, lambda, tau, step)
  theta <- one_step[[1]]
  eta <- one_step[[2]]
  THx[,iter] <- prox_f1(theta, y, tau)
  if (iter > 1){
    rerr[iter] <- norm(as.matrix(THx[,iter] - THx[,iter-1]),'f')/
                    (1 + norm(THx[,iter,drop=FALSE], 'f'))
  }
}
theta_last <- prox_f1(theta, y, tau)

par(mfrow=c(2,1), mar=c(3,4,1,1))
plot(log(rerr), type="l")

plot(simData$x,simData$f,type='l',col='blue',
ylim=c(min(y),max(y)), lwd=3,ylab="", xlab="")
points(simData$x,y, cex=.6)
lines(simData$x,theta_last,col='red', lwd=3)

```