# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib detrendr
#' @importFrom Rcpp evalCpp
#' 
#' @title
#' \code{prox_quantile} computes the proximal mapping of the check function.
#'
#' @param w input
#' @param tau quantile parameter
#' @param alpha scale parameter
#' @examples
#' set.seed(12345)
#' n <- 1e3
#' w <- seq(-3, 3, length.out=n)
#' tau <- 0.5
#' alpha <- 2
#' prox_out <- prox_quantile(w, tau, alpha)
#' plot(w, prox_out, type='l', main=expression(paste(tau," = ")))
#'
#' tau <- 0.05
#' alpha <- 2
#' prox_out <- prox_quantile(w, tau, alpha)
#' plot(w, prox_out, type='l', main=expression(paste(tau," = ")))
#' @export
prox_quantileC <- function(w, tau, alpha) {
    .Call('detrendr_prox_quantileC', PACKAGE = 'detrendr', w, tau, alpha)
}

